root: true
env:
  es2021: true
  node: true
  jest: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
plugins:
  - '@typescript-eslint'
  - prettier
  - eslint-plugin-import-helpers
  - sonarjs
  - security
extends:
  - airbnb-base
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:sonarjs/recommended
  - plugin:security/recommended-legacy
settings:
  import/resolver:
    node:
      extensions: ['.js', '.jsx', '.ts', '.tsx']
overrides:
  - files:
      - src/**/*.test.js
    rules:
      sonarjs/no-duplicate-string: off
rules:
  import/prefer-default-export: off
  no-useless-constructor: off
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: es5
      semi: true
      tabWidth: 4
      printWidth: 100
  import-helpers/order-imports:
    - warn
    - newlinesBetween: 'always'
      groups:
        - 'module'
        - '/^@pulumi/'
        - '/^@soufantech/'
        - ['parent', 'sibling', 'index']
      alphabetize:
        order: 'asc'
        ignoreCase: true
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
